spring:
  application:
    name: accounts
        
accounts:
 message: "welcome to accounts prod micorservices"
 contactDetails: 
  name: "janaki ramayya"
  email: "janakiramayya978@gmail.com"
 onCallSupport:
  -9182802103
  -8978715972
build:
 version:1.2
